#common configuration files on server or on github.
#import using spring:
#  config:
#    import:
#    - optional:configserver:http://localhost:8085
spring:
  application:
    name: UserService_ConfigServer

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
